<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class T04_package_model extends CI_Model
{

    public $table = 't04_package';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    function get_price($id, $night)
    {
        // code...
        $package_row = $this->get_by_id($id);

        switch ($night) {
            case 3:
                $mata_uang = $package_row->ln3n_mata_uang;
                $price = $package_row->ln3n_harga;
                break;
            case 6:
                $mata_uang = $package_row->ln6n_mata_uang;
                $price = $package_row->ln6n_harga;
                break;
            case 1:
                $mata_uang = $package_row->ln1n_mata_uang;
                $price = $package_row->ln1n_harga * $night;
                break;
            default:
                $mata_uang = $package_row->ln1n_mata_uang;
                $price = $package_row->ln1n_harga * $night;
        }

        $this->db->where('id', $mata_uang);
        $t00_mata_uang_data = $this->db->get('t00_mata_uang')->row();
        // pre($t00_mata_uang_data); exit;

        return json_encode(array(
            'price_n_kode' => $t00_mata_uang_data->kode . ' ' . $price,
            'price_only' => $price,
            'mata_uang' => $mata_uang,
        ));
        // return $mata_uang;
    }

    // get_all_by_periode
    function get_all_by_periode($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('periode', $this->db->get($this->table)->row()->periode);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by kode
    function get_by_kode($kode)
    {
        $this->db->where('kode', $kode);
        return $this->db->get($this->table)->row();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
    	$this->db->or_like('periode', $q);
    	$this->db->or_like('kode', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('ln3n_mata_uang', $q);
    	$this->db->or_like('ln3n_harga', $q);
    	$this->db->or_like('ln6n_mata_uang', $q);
    	$this->db->or_like('ln6n_harga', $q);
    	$this->db->or_like('ln1n_mata_uang', $q);
    	$this->db->or_like('ln1n_harga', $q);
    	$this->db->or_like('dnrb_mata_uang', $q);
    	$this->db->or_like('dnrb_harga', $q);
    	$this->db->or_like('dnfb_mata_uang', $q);
    	$this->db->or_like('dnfb_harga', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('periode', $q);
    	$this->db->or_like('kode', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('ln3n_mata_uang', $q);
    	$this->db->or_like('ln3n_harga', $q);
    	$this->db->or_like('ln6n_mata_uang', $q);
    	$this->db->or_like('ln6n_harga', $q);
    	$this->db->or_like('ln1n_mata_uang', $q);
    	$this->db->or_like('ln1n_harga', $q);
    	$this->db->or_like('dnrb_mata_uang', $q);
    	$this->db->or_like('dnrb_harga', $q);
    	$this->db->or_like('dnfb_mata_uang', $q);
    	$this->db->or_like('dnfb_harga', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T04_package_model.php */
/* Location: ./application/models/T04_package_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-08-18 06:20:20 */
/* http://harviacode.com */
