<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class T36_pembayaran_oleh_model extends CI_Model
{

    public $table = 't36_pembayaran_oleh';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all by bkm_detail
    function get_all_by_bkm_detail($bkm_detail)
    {
        $this->db->join('t31_bkm_detail', 't31_bkm_detail.id = '.$this->table.'.'.'paid_for', 'left');
        $this->db->join('t04_package', 't04_package.id = t31_bkm_detail.package', 'left');
        $this->db->join('t00_mata_uang', 't00_mata_uang.id = t31_bkm_detail.mata_uang', 'left');
        $this->db->where('bkm_detail', $bkm_detail);
        $this->db->order_by($this->table.'.'.$this->id, $this->order);
        $this->db->select(
            $this->table.'.*
            , t04_package.nama as package_nama
            , t31_bkm_detail.night
            , t31_bkm_detail.name
            , t00_mata_uang.kode as mata_uang_kode
            , t31_bkm_detail.price
            '
        );
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('bkm_detail', $q);
        $this->db->or_like('paid_for', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('bkm_detail', $q);
        $this->db->or_like('paid_for', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T36_pembayaran_oleh_model.php */
/* Location: ./application/models/T36_pembayaran_oleh_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-08-26 20:39:43 */
/* http://harviacode.com */
